### ISSUE TITLE
amazeballs

### ISSUE THREAD

**Issue by steveoh** [sindresorhus/fast-cli#1]
you are seriously a very generous person. Thanks.

but...

```js
module.js:327
    throw err;
    ^

Error: Cannot find module './api'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/fast-cli/cli.js:8:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

node 4.4.4
npm 3.8.9

**Comment by rmichnik** [comment]
Same here

node v6.2.0
npm 3.8.9

**Comment by sindresorhus** [comment]
Ugh, [npm being buggy and publishing corrupt packages on Node.js 6](https://github.com/npm/npm/issues/5082#issuecomment-216623149) :(

Should be fixed now. Try installing again.

**Comment by sindresorhus** [comment]
Here's a cute unicorn for the trouble. Enjoy ;)

![unicorn20](https://cloud.githubusercontent.com/assets/170270/15376314/7e23727c-1d7e-11e6-837b-ad8354389bcf.gif)
