### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by jackinthesandbox** [sindresorhus/fast-cli#21]
I installed fast-cli with "npm install --global fast-cli" and upon running "fast" I received the following error. 

```
/usr/local/lib/node_modules/fast-cli/api.js:6
async function init(browser, page, observer, prevSpeed) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/fast-cli/cli.js:8:13)
    at Module._compile (module.js:541:32)
```

**Comment by sindresorhus** [comment]
From the readme:

> Ensure you have Node.js version 8+ installed.
