### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by insign** [sindresorhus/fast-cli#22]
My node/nodejs version: v8.9.1
NPM: 5.5.1

Ubuntu: I tried in a Xenial Xerus and a Bionic Beaver

```forge@ckp-db:~$ sudo npm i -g fast-cli
/usr/bin/fast -> /usr/lib/node_modules/fast-cli/cli.js

> puppeteer@0.12.0 install /usr/lib/node_modules/fast-cli/node_modules/puppeteer
> node install.js

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/fast-cli/node_modules/puppeteer/.local-chromium'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.downloadRevision (/usr/lib/node_modules/fast-cli/node_modules/puppeteer/utils/ChromiumDownloader.js:99:10)
    at Object.<anonymous> (/usr/lib/node_modules/fast-cli/node_modules/puppeteer/install.js:45:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.12.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@0.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/forge/.npm/_logs/2017-12-01T14_40_11_061Z-debug.log
```

**Comment by sindresorhus** [comment]
Use https://github.com/npm/npm/issues for npm support.

**Comment by rlue** [comment]
Per [this thread on Puppeteer](https://github.com/GoogleChrome/puppeteer/issues/375#issuecomment-363466257), you can manually install the dependency with

    $ sudo npm install -g puppeteer@0.12.0 --unsafe-perm=true

before installing fast-cli.

**Comment by sourcevault** [comment]
same issue
