### ISSUE TITLE
Sytax Error when running

### ISSUE THREAD

**Issue by river226** [sindresorhus/fast-cli#24]
```
$ fast
/usr/local/lib/node_modules/fast-cli/api.js:6
async function init(browser, page, observer, prevSpeed) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/fast-cli/cli.js:8:13)
```
npm@3.10.10

**Comment by sindresorhus** [comment]
Upgrade Node
