### ISSUE TITLE
I get syntax error when running.

### ISSUE THREAD

**Issue by Anu-cool-007** [sindresorhus/fast-cli#26]
```
/usr/lib/node_modules/fast-cli/cli.js:52
(async () => {
       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

Is it something with the code?

**Comment by Anu-cool-007** [comment]
Guess I just had Node installation not supporting async functions :P
