### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by YannBertrand** [sindresorhus/fast-cli#3]
`$ sudo npm install -g fast-cli`

node@0.12.10
npm@2.14.9

`$ fast` or `$ fast --help` produce

```
/usr/lib/node_modules/fast-cli/cli.js:3
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by YannBertrand** [comment]
If you encounter this error, you should upgrade to node@4.0 at least.
