### ISSUE TITLE
Add mininmum node version requirement

### ISSUE THREAD

**Issue by magicmark** [sindresorhus/fast-cli#4]
too lazy for a pull request but you probably want something like

```
{ "engines" : { "node" : ">=5.0" } }
```

in package.json to avoid

```
➜  ~ fast

/usr/local/lib/node_modules/fast-cli/cli.js:3
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by sindresorhus** [comment]
Uhm, https://github.com/sindresorhus/fast-cli/blob/0260a5549028ca8f05bec609327082092e10c728/package.json#L16
