### ISSUE TITLE
Fails to install on Centos 8

### ISSUE THREAD

**Issue by twiclo** [sindresorhus/fast-cli#48]
```
[root@toph twilcox]# node --version
v12.16.2
[root@toph twilcox]# npm --version
6.14.4
```

```
3656 silly install puppeteer@1.20.0
3657 info lifecycle puppeteer@1.20.0~install: puppeteer@1.20.0
3658 verbose lifecycle puppeteer@1.20.0~install: unsafe-perm in lifecycle false
3659 verbose lifecycle puppeteer@1.20.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/fast-cli/node_modules/puppeteer/node_modules/.bin:/usr/lib/node_modules/fast-cli/node_modules/.bin:/usr/lib/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
3660 verbose lifecycle puppeteer@1.20.0~install: CWD: /usr/lib/node_modules/fast-cli/node_modules/puppeteer
3661 silly lifecycle puppeteer@1.20.0~install: Args: [ '-c', 'node install.js' ]
3662 silly lifecycle puppeteer@1.20.0~install: Returned: code: 1  signal: null
3663 info lifecycle puppeteer@1.20.0~install: Failed to exec install script
3664 timing action:install Completed in 172ms
3665 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
3666 timing stage:rollbackFailedOptional Completed in 98ms
3667 timing stage:runTopLevelLifecycles Completed in 4663ms
3668 verbose stack Error: puppeteer@1.20.0 install: `node install.js`
3668 verbose stack Exit status 1
3668 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3668 verbose stack     at EventEmitter.emit (events.js:310:20)
3668 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3668 verbose stack     at ChildProcess.emit (events.js:310:20)
3668 verbose stack     at maybeClose (internal/child_process.js:1021:16)
3668 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
3669 verbose pkgid puppeteer@1.20.0
3670 verbose cwd /home/twilcox
3671 verbose Linux 4.4.217-1.el7.elrepo.x86_64
3672 verbose argv "/usr/bin/node" "/bin/npm" "install" "--global" "fast-cli"
3673 verbose node v12.16.2
3674 verbose npm  v6.14.4
3675 error code ELIFECYCLE
3676 error errno 1
3677 error puppeteer@1.20.0 install: `node install.js`
3677 error Exit status 1
3678 error Failed at the puppeteer@1.20.0 install script.
3678 error This is probably not a problem with npm. There is likely additional logging output above.
3679 verbose exit [ 1, true ]```

**Comment by sindresorhus** [comment]
This is a problem with installing Puppeteer.

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
