### ISSUE TITLE
Error: Cannot find module './ui'

### ISSUE THREAD

**Issue by erkanzileli** [sindresorhus/fast-cli#63]
Hi there! I have seen an issue while using it. Do you know how to solve that?

```sh
~ npm install --global fast-cli
/Users/erkan.zileli/.nvm/versions/node/v12.18.3/bin/fast -> /Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/cli.js
npm WARN notsup Unsupported engine for fast-cli@3.0.0: wanted: {"node":">=12.20"} (current: {"node":"12.18.3","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: fast-cli@3.0.0

+ fast-cli@3.0.0
updated 1 package in 11.29s
~ fast
/Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module './ui'
Require stack:
- /Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at resolveFileName (/Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/node_modules/resolve-from/index.js:31:9)
    at module.exports (/Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/node_modules/resolve-from/index.js:34:41)
    at importJsx (/Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/node_modules/import-jsx/index.js:20:21)
    at Object.<anonymous> (/Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/cli.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/erkan.zileli/.nvm/versions/node/v12.18.3/lib/node_modules/fast-cli/noop.js'
  ]
}
```

**Comment by wangxdmm** [comment]
+1
