### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by dodalovic** [sindresorhus/fast-cli#72]
``

`fast -u
/home/dodalovic/.nvm/versions/node/v17.3.0/lib/node_modules/fast-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at filename (/home/dodalovic/.nvm/versions/node/v17.3.0/lib/node_modules/fast-cli/node_modules/import-jsx/cache.js:23:22)
    at handleCache (/home/dodalovic/.nvm/versions/node/v17.3.0/lib/node_modules/fast-cli/node_modules/import-jsx/cache.js:43:36)
    at module.exports (/home/dodalovic/.nvm/versions/node/v17.3.0/lib/node_modules/fast-cli/node_modules/import-jsx/cache.js:97:9)
    at Module.module._compile (/home/dodalovic/.nvm/versions/node/v17.3.0/lib/node_modules/fast-cli/node_modules/import-jsx/index.js:37:19)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> (/home/dodalovic/.nvm/versions/node/v17.3.0/lib/node_modules/fast-cli/node_modules/import-jsx/index.js:49:3)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
```

**Comment by sindresorhus** [comment]
You're using the bleeding edge of Node.js, which often have issues. Try the latest stable, which is Node.js 16.

**Comment by dodalovic** [comment]
ah, ok. 
Maybe it would be cool to update the docs. lemme try
